### ISSUE TITLE
Wrong loader length if overfit=True

### ISSUE THREAD

**Issue by Nimrais** [catalyst-team/catalyst#1301] opened 2021-09-20 19:25 UTC
## 🐛 Bug Report

`runner.train(
    ...
    overfit=True
)`

The runner.loader_sample_len is wrong currently we will have loader length from the original loader.
But we must have the first batch size * a number of batches.

### How To Reproduce

Take any loader and after runner.train check the train loader length with overfit=True

### Expected behavior
we must have the first batch size * a number of batches.

### Environment
Not needed

### Checklist
- [x] bug description
- [ ] steps to reproduce
- [x] expected behavior
- [x] environment
- [ ] code sample / screenshots
  
### FAQ
Please review the FAQ before submitting an issue:
- [x] I have read the [documentation and FAQ](https://catalyst-team.github.io/catalyst/)
- [x] I have reviewed the [minimal examples section](https://github.com/catalyst-team/catalyst#minimal-examples)
- [x] I have checked the [changelog](https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md) for main framework updates
- [x] I have read the [contribution guide](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md)
- [x] I have joined [Catalyst slack (#__questions channel)](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for issue discussion

**Comment by ditwoo** [comment] 2021-09-20 19:34
I think in the current implementation it's not a bug - it's a feature)
Batch overfit is a functionality that allows you to check fast that the model can learn on the same data or not.

**Comment by Scitator** [comment] 2021-09-23 04:30
We still should count the sample size in a right way ;)

**Comment by Scitator** [comment] 2021-11-22 07:17
should be fixed ;)

**Closed as completed by Scitator** 2021-11-22 07:17 UTC
Labels: bug, help wanted, wontfix
