### ISSUE TITLE
[Feature] Additive Margin Softmax

### ISSUE THREAD

**Issue by Atharva-Phatak** [catalyst-team/catalyst#1125] opened 2021-03-20 09:10 UTC
## 🚀 Feature Request

I would like to add [Additive Margin Softmax](https://arxiv.org/pdf/1801.05599v4.pdf) to its amazing list of various 'Face' losses.

### Motivation

Catalyst has nice support for metric learning and I would like catalyst modules to be expanded more and possibly have most SOTA implementations of Face metrics.

### Proposal

Just like how ArcFace and CosFace are implemented in the catalyst library, I would like to add AM-Softmax to this list as well. Possibly other metric learning modules if provided the opportunity.

### Additional context
Additive margin softmax was used in 2nd place solution of a [Kaggle](https://www.kaggle.com/c/humpback-whale-identification/discussion/83885) competition.

### Checklist
- [x] feature proposal description.
- [x] motivation.
- [ ] extra proposal context / proposal alternatives review.
- [x] I know, that I could [join Catalyst slack (#__questions channel)](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for issue discussion.

### Note 
 
This goes without saying I want to implement it

**Comment by Scitator** [comment] 2021-03-21 07:47
Hi,

the idea looks great, especially if you are interested in the implementation contribution :)

I also think @Ditwoo would be interested in too.

**Comment by Atharva-Phatak** [comment] 2021-03-21 07:49
Hi, yes I have a working implementation ready, I can write up some tests for it and create a pr.

**Comment by Scitator** [comment] 2021-03-21 07:51
That's would be great,
btw, you could check current tests for the "Faces" family [here](https://github.com/catalyst-team/catalyst/blob/master/catalyst/contrib/nn/tests/test_modules.py)

**Comment by Atharva-Phatak** [comment] 2021-03-21 07:52
I will take look at it for sure.

**Comment by Atharva-Phatak** [comment] 2021-03-21 14:57
@Scitator I took a look at the tests, the tests seems to be well designed. So no worries. I will start with implementation and create PR soon.

**Comment by Atharva-Phatak** [comment] 2021-03-21 17:12
@Scitator can you give me some tips on how to pass the codestyle ?
Here are the steps I followed.
1) I forked the latest repo and cloned it
2) installed the dependencies for requirements.txt and requirements-dev.txt
3) I run catalyst-make-codestyle first and the catalyst-check-codestyle
4) Files seem to be reformatted but flake8 errors persist. Also, there are no errors in the file which I added.(Last time also the same thing happened with codestyle, hence I want to do it perfectly this time.)

Hence I wanted some help to make codestyle do not throw any error.

**Comment by Scitator** [comment] 2021-03-21 19:04
sorry, but could not reproduce the issue: https://colab.research.google.com/drive/1JCGTVvWlrIsLXMPRRRSWiAstSLic4nbA?usp=sharing

**Comment by Atharva-Phatak** [comment] 2021-03-22 19:51
@Scitator Thank you now my codestyle is compatible. But when I run tests using pytest .. I get the following error 
 ImportError: cannot import name 'SummaryWriter' from 'tensorboardX' (unknown location)

Here are the specs of my env
platform linux 20.04 -- Python 3.8.5, pytest-5.3.1, py-1.10.0, pluggy-0.13.1

Any tips to resolve it ?

**Comment by Scitator** [comment] 2021-03-23 05:10
I think, you still have to reinstall the requirements `TensorboardX` is must-have one :)
https://github.com/catalyst-team/catalyst/blob/master/requirements/requirements.txt#L13

**Comment by Scitator** [comment] 2021-03-29 18:17
looks like merged ;)

**Closed as completed by Scitator** 2021-03-29 18:17 UTC
Labels: enhancement, help wanted
